
version: 2

models:
  - name: customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
models:
  - name: orders
    columns:
      - name: status
        tests:
          - accepted_values:
              values:
                - placed
                - shipped
                - completed
                - returned
models:
  - name: orders
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('customers')
              field: id
